# Generated by Django 4.2.2 on 2023-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=None),
        ),
    ]
