# Generated by Django 4.2.2 on 2023-06-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, default='Doe', max_length=50),
        ),
    ]
