# Generated by Django 4.2.2 on 2023-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_employee_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jun', 'Junior'), ('mid', 'Middle'), ('sen', 'Senior')], default='jun', max_length=3),
        ),
    ]
