# Generated by Django 4.2.2 on 2023-06-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_profile_id_alter_profile_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-first_name'], 'verbose_name_plural': 'My Employees'},
        ),
    ]
