# Generated by Django 4.2.2 on 2023-06-17 12:52

from django.db import migrations
from django.utils.text import slugify


def add_slugs(apps, schema_editor):
    # can't import Department here, because it would be imported from 'models_demos/web/models.py',
    # which is not the same as the current 'models.py'
    Department = apps.get_model('web', 'Department')
    departments = Department.objects.all()
    for department in departments:
        department.slug = slugify(department.name)
    Department.objects.bulk_update(departments, ['slug'])


def remove_slugs(apps, schema_editor):
    Department = apps.get_model('web', 'Department')
    departments = Department.objects.all()
    for department in departments:
        department.slug = None
    Department.objects.bulk_update(departments, ['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_department_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, remove_slugs)
    ]
