# Generated by Django 4.2.4 on 2023-08-16 11:30

import django.core.validators
from django.db import migrations, models
import retake_exam_project.profile_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[retake_exam_project.profile_app.validators.consist_only_of_letters_func])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=45)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), retake_exam_project.profile_app.validators.contain_at_least_one_digit_func])),
            ],
        ),
    ]
