# Generated by Django 4.2.4 on 2023-08-16 11:53

import django.core.validators
from django.db import migrations, models
import retake_exam_project.profile_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[retake_exam_project.profile_app.validators.consist_only_of_letters_func]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
