# Generated by Django 4.2.2 on 2023-06-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_documentmodel_imagemodel_alter_todomodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='documents',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
