# Generated by Django 4.2.4 on 2023-08-16 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import retake_exam_project.event_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Festivals', 'Festivals'), ('Conferences', 'Conferences'), ('Performing Art', 'Performing Art'), ('Concerts', 'Concerts'), ('Theme Party', 'Theme Party'), ('Other', 'Other')], max_length=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(validators=[retake_exam_project.event_app.validators.prevent_users_from_selecting_a_date_earlier_than_today_func])),
                ('event_image', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profilemodel')),
            ],
        ),
    ]
