# Generated by Django 4.2.2 on 2023-06-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='def', max_length=50),
            preserve_default=False,
        ),
    ]
